# Generated by Django 4.1 on 2022-11-24 00:06

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                ("tof_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "background_tof",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("poster_tof", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("lesstext", models.TextField(blank=True, null=True)),
                ("moretext", models.TextField(blank=True, null=True)),
                (
                    "couleur",
                    colorfield.fields.ColorField(
                        default="#f9f5f5", image_field=None, max_length=18, samples=None
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, null=True)),
                (
                    "genre_1",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Aventure", "Aventure"),
                            ("Comedie", "Comedie"),
                            ("Drama", "Drama"),
                            ("Horreur", "Horreur"),
                            ("Romance", "Romance"),
                            ("Sci-fi", "Sci-fi"),
                            ("Slice of life", "Slice of life"),
                            ("Mystère", "Mystère"),
                            ("Seinen", "Seinen"),
                            ("Isekai", "Isekai"),
                            ("Shonen", "Shonen"),
                            ("Film", "Film"),
                        ],
                        default="specifiez le genre d'animé s'il vous plait",
                        max_length=50,
                        verbose_name="genre",
                    ),
                ),
                (
                    "genre_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Action", "Action"),
                            ("Aventure", "Aventure"),
                            ("Comedie", "Comedie"),
                            ("Drama", "Drama"),
                            ("Horreur", "Horreur"),
                            ("Romance", "Romance"),
                            ("Sci-fi", "Sci-fi"),
                            ("Slice of life", "Slice of life"),
                            ("Mystère", "Mystère"),
                            ("Seinen", "Seinen"),
                            ("Isekai", "Isekai"),
                            ("Shonen", "Shonen"),
                            ("Film", "Film"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="genre",
                    ),
                ),
                (
                    "genre_3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Action", "Action"),
                            ("Aventure", "Aventure"),
                            ("Comedie", "Comedie"),
                            ("Drama", "Drama"),
                            ("Horreur", "Horreur"),
                            ("Romance", "Romance"),
                            ("Sci-fi", "Sci-fi"),
                            ("Slice of life", "Slice of life"),
                            ("Mystère", "Mystère"),
                            ("Seinen", "Seinen"),
                            ("Isekai", "Isekai"),
                            ("Shonen", "Shonen"),
                            ("Film", "Film"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="genre",
                    ),
                ),
                (
                    "genre_4",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Action", "Action"),
                            ("Aventure", "Aventure"),
                            ("Comedie", "Comedie"),
                            ("Drama", "Drama"),
                            ("Horreur", "Horreur"),
                            ("Romance", "Romance"),
                            ("Sci-fi", "Sci-fi"),
                            ("Slice of life", "Slice of life"),
                            ("Mystère", "Mystère"),
                            ("Seinen", "Seinen"),
                            ("Isekai", "Isekai"),
                            ("Shonen", "Shonen"),
                            ("Film", "Film"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="genre",
                    ),
                ),
                ("genres", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "posteur",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("genre_1", "genre_2", "genre_3", "genre_4")},
            },
        ),
        migrations.CreateModel(
            name="la_video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode",
                    models.PositiveIntegerField(
                        verbose_name="===> Ecrivez le chiffre correspondant a l'episode"
                    ),
                ),
                (
                    "saison",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="la saison correspondant a l'episode",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("ref", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "nom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenu.video",
                    ),
                ),
            ],
        ),
    ]
