# Generated by Django 4.1 on 2022-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="genre_1",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Aventure", "Aventure"),
                    ("Comedie", "Comedie"),
                    ("Drama", "Drama"),
                    ("Horreur", "Horreur"),
                    ("Romance", "Romance"),
                    ("Sci-fi", "Sci-fi"),
                    ("Slice of life", "Slice of life"),
                    ("Mystere", "Mystere"),
                    ("Seinen", "Seinen"),
                    ("Isekai", "Isekai"),
                    ("Shonen", "Shonen"),
                    ("Film", "Film"),
                ],
                default="specifiez le genre d'animé s'il vous plait",
                max_length=50,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="genre_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Action", "Action"),
                    ("Aventure", "Aventure"),
                    ("Comedie", "Comedie"),
                    ("Drama", "Drama"),
                    ("Horreur", "Horreur"),
                    ("Romance", "Romance"),
                    ("Sci-fi", "Sci-fi"),
                    ("Slice of life", "Slice of life"),
                    ("Mystere", "Mystere"),
                    ("Seinen", "Seinen"),
                    ("Isekai", "Isekai"),
                    ("Shonen", "Shonen"),
                    ("Film", "Film"),
                ],
                max_length=50,
                null=True,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="genre_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Action", "Action"),
                    ("Aventure", "Aventure"),
                    ("Comedie", "Comedie"),
                    ("Drama", "Drama"),
                    ("Horreur", "Horreur"),
                    ("Romance", "Romance"),
                    ("Sci-fi", "Sci-fi"),
                    ("Slice of life", "Slice of life"),
                    ("Mystere", "Mystere"),
                    ("Seinen", "Seinen"),
                    ("Isekai", "Isekai"),
                    ("Shonen", "Shonen"),
                    ("Film", "Film"),
                ],
                max_length=50,
                null=True,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="genre_4",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Action", "Action"),
                    ("Aventure", "Aventure"),
                    ("Comedie", "Comedie"),
                    ("Drama", "Drama"),
                    ("Horreur", "Horreur"),
                    ("Romance", "Romance"),
                    ("Sci-fi", "Sci-fi"),
                    ("Slice of life", "Slice of life"),
                    ("Mystere", "Mystere"),
                    ("Seinen", "Seinen"),
                    ("Isekai", "Isekai"),
                    ("Shonen", "Shonen"),
                    ("Film", "Film"),
                ],
                max_length=50,
                null=True,
                verbose_name="genre",
            ),
        ),
    ]
