# Generated by Django 4.1 on 2022-12-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0002_alter_video_genre_1_alter_video_genre_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="background_tof",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="poster_tof",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="tof_url",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
