# Generated by Django 4.1 on 2023-08-17 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0003_alter_video_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="la_video",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
