# Generated by Django 4.1 on 2023-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0004_la_video_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="special_cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("videos", models.ManyToManyField(null=True, to="contenu.video")),
            ],
        ),
    ]
