# Generated by Django 4.1 on 2023-09-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0005_cluster_special_cluster"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="cluster",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenu.cluster",
            ),
        ),
    ]
