# Generated by Django 4.1 on 2023-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0006_video_cluster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="special_cluster",
            name="videos",
            field=models.ManyToManyField(default=None, to="contenu.video"),
        ),
    ]
