# Generated by Django 4.1 on 2023-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0007_alter_special_cluster_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="centroid",
            field=models.BinaryField(default=None, null=True),
        ),
    ]
