# Generated by Django 4.1 on 2023-11-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenu', '0009_video_feature_array_video_params_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='la_video',
            name='direct_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
