# Generated by Django 4.1 on 2023-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_views_inTimeframe", models.IntegerField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
