# Generated by Django 4.1 on 2023-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Not_brief_connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_user_staying", models.IntegerField(default=1)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="webtraffic",
            name="num_views_inTimeframe",
            field=models.IntegerField(default=1),
        ),
    ]
