# Generated by Django 4.1 on 2023-04-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_not_brief_connection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webtraffic",
            name="user_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
