# Generated by Django 4.1 on 2023-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_webtraffic_user_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtraffic",
            name="user_info",
            field=models.TextField(default=" "),
        ),
    ]
