# Generated by Django 4.1 on 2022-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenu", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="calendrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=10)),
                ("Dimanche", models.CharField(default="N/A", max_length=50)),
                ("Lundi", models.CharField(default="N/A", max_length=50)),
                ("Mardi", models.CharField(default="N/A", max_length=50)),
                ("Mercredi", models.CharField(default="N/A", max_length=50)),
                ("Jeudi", models.CharField(default="N/A", max_length=50)),
                ("Vendredi", models.CharField(default="N/A", max_length=50)),
                ("Samedi", models.CharField(default="N/A", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="onglet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=60, null=True)),
                ("onglet1", models.ManyToManyField(blank=True, to="contenu.video")),
            ],
        ),
        migrations.CreateModel(
            name="affichage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "poster",
                    models.ManyToManyField(
                        blank=True,
                        to="contenu.video",
                        verbose_name="Les posters a afficher",
                    ),
                ),
                ("to_display", models.ManyToManyField(blank=True, to="gerant.onglet")),
            ],
        ),
    ]
