# Generated by Django 4.1 on 2023-05-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onglet",
            name="description_onglet",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Small description for the content of the onglet",
            ),
        ),
       
        migrations.AddField(
            model_name="onglet",
            name="order_id",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
