# Generated by Django 4.1 on 2023-05-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerant", "0003_onglet_link_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onglet",
            name="link_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Action", "Action"),
                    ("Aventure", "Aventure"),
                    ("Comedie", "Comedie"),
                    ("Drama", "Drama"),
                    ("Horreur", "Horreur"),
                    ("Romance", "Romance"),
                    ("Sci-fi", "Sci-fi"),
                    ("Slice of life", "Slice of life"),
                    ("Mystere", "Mystere"),
                    ("Seinen", "Seinen"),
                    ("Isekai", "Isekai"),
                    ("Shonen", "Shonen"),
                    ("Sport", "Sport"),
                    ("Fantaisie", "Fantaisie"),
                    ("Shojo", "Shojo"),
                    ("Thriller", "Thriller"),
                    ("Combat", "Combat"),
                    ("School life", "School life"),
                    ("Music", "Music"),
                    ("Ecchi", "Ecchi"),
                    ("Autres", "Autres"),
                    ("Classique", "Classique"),
                    ("Film", "Film"),
                ],
                max_length=50,
                null=True,
                verbose_name="conduit vers : ",
            ),
        ),
    ]
