# Generated by Django 4.1 on 2023-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0002_alter_video_unique_together_la_video_special_and_more"),
        ("identifier", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="role",
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="anime_prefere",
            field=models.ManyToManyField(default=None, to="contenu.video"),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_friend",
            field=models.BooleanField(default=False),
        ),
    ]
