# Generated by Django 4.1 on 2022-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="anime_prefere",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
