# Generated by Django 4.1 on 2023-09-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0002_remove_utilisateur_role_utilisateur_anime_prefere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_cluster_1', models.IntegerField(default=None, null=True)),
                ('fav_cluster_2', models.IntegerField(default=None, null=True)),
                ('fav_cluster_3', models.IntegerField(default=None, null=True)),
                ('centroid', models.BinaryField(default=None, null=True)),
            ],
        ),
    ]
