# Generated by Django 4.1 on 2022-09-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0002_utilisateur_anime_prefere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="anime_prefere",
            field=models.CharField(max_length=100),
        ),
    ]
