# Generated by Django 4.1 on 2022-09-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0003_alter_utilisateur_anime_prefere"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="anime_prefere",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
