# Generated by Django 4.1 on 2022-09-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0004_utilisateur_is_staff_utilisateur_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="has_module_perms",
            field=models.BooleanField(default=False),
        ),
    ]
