# Generated by Django 4.1 on 2022-09-30 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0006_remove_utilisateur_has_module_perms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="utilisateur", old_name="is_staff", new_name="is_admin",
        ),
        migrations.RemoveField(model_name="utilisateur", name="is_superuser",),
    ]
