# Generated by Django 4.1 on 2022-11-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0007_rename_is_staff_utilisateur_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_friend",
            field=models.BooleanField(default=False),
        ),
    ]
