# Generated by Django 4.1 on 2022-11-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenu", "0001_initial"),
        ("identifier", "0008_utilisateur_is_friend"),
    ]

    operations = [
        migrations.RemoveField(model_name="utilisateur", name="anime_prefere",),
        migrations.AddField(
            model_name="utilisateur",
            name="anime_prefere",
            field=models.ManyToManyField(default=None, to="contenu.video"),
        ),
    ]
