# Generated by Django 4.1 on 2022-11-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identifier", "0009_remove_utilisateur_anime_prefere_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="utilisateur", name="role",),
    ]
