# Generated by Django 4.2.7 on 2023-12-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='start_date',
        ),
        migrations.AddField(
            model_name='anime',
            name='english_title',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='index',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='other_name',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='producers',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='year_interaction',
            field=models.IntegerField(default=2007),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
