# Generated by Django 4.2.7 on 2023-12-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_classification_remove_anime_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='nsfw',
        ),
        migrations.AddField(
            model_name='anime',
            name='classification',
            field=models.ManyToManyField(default=None, to='recommendations.classification'),
        ),
    ]
